#!  /bin/bash

BLOCK_SIZE=1024

#iterate through each  block size
# until 32 MB block size
while [ $BLOCK_SIZE -le 33554432 ]
do

  QUEUE_DEPTH=1

  #iterate through each queue deapth
  while [ $QUEUE_DEPTH -le 256 ]
  do

    # Initialize counter variable
    COUNT=1

    touch "report/qd_bs/qducp_${QUEUE_DEPTH}_${BLOCK_SIZE}.csv"

    # Iterate over each item
    while [ $COUNT -le 5 ]
    do
        echo "QD = $QUEUE_DEPTH BS = $BLOCK_SIZE Count = $COUNT"
        make clean
        make DEBUG=0 "QD=$QUEUE_DEPTH" "BS=$BLOCK_SIZE"
        # Perform some action on the item
        # ...
        ./bin/myucp -t -i virtualdisk/largefile -o virtualdisk/largefile_copy >> "report/qd_bs/qducp_${QUEUE_DEPTH}_${BLOCK_SIZE}.csv" 2>&1
        ((COUNT++))
    done

    ((QUEUE_DEPTH*=2))

  done

  ((BLOCK_SIZE*=32))

done

