#!  /bin/bash



BS=33554432 
QUEUE_DEPTH=16

#iterate through each queue deapth

# Initialize counter variable

# Iterate over each item

file_sizes=("1kb" "32kb" "1mb" "32mb" "largefile")
#file_sizes=("1kb")

for fl in "${file_sizes[@]}"
do

  COUNT=1

  while [ $COUNT -le 5 ]
  do

    echo "Count = $COUNT file size = $fl"

    echo "Testing io_uring copy"

    sudo ./bash/mountfs
    echo "BS = $BS QUEUE_DEPTH = $QUEUE_DEPTH "
    make clean > /dev/null 2>&1
    make DEBUG=0 "BS=$BS" "QUEUE_DEPTH=$QUEUE_DEPTH"  > /dev/null 2>&1
    # Perform some action on the item
    # ...
    sudo fincore virtualdisk/${fl} 
    time ./bin/myucp -i virtualdisk/$fl -o virtualdisk/{$fl}_copy 
    diff virtualdisk/$fl virtualdisk/{$fl}_copy

    sudo ./bash/umountfs


    echo "Testing system copy"

    sudo ./bash/mountfs
    sudo fincore virtualdisk/$fl
    time cp virtualdisk/${fl} virtualdisk/${fl}_copy 
    diff virtualdisk/${fl} virtualdisk/${fl}_copy

    sudo ./bash/umountfs

    ((COUNT++))

  done
done