#!  /bin/bash

QUEUE_DEPTH=1

#iterate through each queue deapth
while [ $QUEUE_DEPTH -le 256 ]
do

  # Initialize counter variable
  COUNT=1

  touch "report/qducp_$QUEUE_DEPTH.csv"

  # Iterate over each item
  while [ $COUNT -le 5 ]
  do
      echo "QD = $QUEUE_DEPTH Count = $COUNT"
      make clean
      make DEBUG=0 "QD=$QUEUE_DEPTH"
      # Perform some action on the item
      # ...
      ./bin/myucp -t -i virtualdisk/largefile -o virtualdisk/largefile_copy >> "report/qducp_$QUEUE_DEPTH.csv" 2>&1
      ((COUNT++))
  done

  ((QUEUE_DEPTH*=2))

done

