#!  /bin/bash



BS=1024

#iterate through each queue deapth
while [ $BS -le 33554432 ]
do

  # Initialize counter variable
  COUNT=1

  touch "report/bs_ucp_poll/bsucp_$BS.csv"

  # Iterate over each item
  while [ $COUNT -le 5 ]
  do
      echo "BS = $BS Count = $COUNT"
      make clean
      make DEBUG=0 "BS=$BS" "POLL=1"
      # Perform some action on the item
      # ...
      ./bin/myucp -t -i virtualdisk/largefile -o virtualdisk/largefile_copy >> "report/bs_ucp_poll/bsucp_$BS.csv" 2>&1
      ((COUNT++))
  done

  ((BS*=32))

done



#BS=33554432 
#
##iterate through each queue deapth
#while [ $BS -le 33554432 ]
#do
#
#  # Initialize counter variable
#  COUNT=1
#
#  touch "report/bs_cp/bscp_$BS.csv"
#
#  # Iterate over each item
#  while [ $COUNT -le 5 ]
#  do
#      echo "BS = $BS Count = $COUNT"
#      make clean
#      make DEBUG=0 "BS=$BS" 
#      # Perform some action on the item
#      # ...
#      ./bin/mycp -t -i virtualdisk/largefile -o virtualdisk/largefile_copy >> "report/bs_cp/bscp_$BS.csv" 2>&1
#      ((COUNT++))
#  done
#
#  ((BS*=32))
#
#done
#